server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ouer?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root